### ISSUE TITLE
New Federation Attriubute - dsdStudentID

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/validator-service#114]
Please add the dsdStudentId - oid:1.3.6.1.4.1.27691.1.1 attribute to the Attriubte Validator in the optional section.

Attriubte Description: "Student Id used to map a logged in student to their ID in the Universities Student System. This is specificly for the Digitary Service."

**Comment by abrahad** [comment]
Hi Ryan,

As discussed in the morning ,  please add dsdStudentId attribute in the test and production Validator. Thanks.

**Comment by rcaught** [comment]
FYI, this still needs to roll through to prod and have the database updated to know about the attribute.

**Comment by rcaught** [comment]
@abrahad, this is working in the test federation.  Can you please confirm this with somebody who has this attribute.
