### ISSUE TITLE
Confused users!

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/validator-service#124]
I have had two incidents so far of confused IdP admins saying that the old validator gave the a green tick for eduPersonEntitlements (with no values provided) and now with the new validator they get the orange warning (The attribute has not been supplied).

I not sure how to resolve this, happy for ideas...

Possible extend the message that pops up to say that it is ok to have no values provided!

**Comment by rcaught** [comment]
Is it a core attribute?

**Comment by bradleybeddoes** [comment]
Technically it is but not used that much "in reality" outside of IdE queries/responses.

**Comment by rcaught** [comment]
@trsau are you happy to move this to the optional category?

**Comment by vladimir-mencl-eresearch** [comment]
Hi guys,

I just accidentally caught this conversation.

I think it is important for eduPersonEntitlement to stay a Core attribute - as a signal to institutions they need to support this.

My workaround around not receiving a value at the validator has been to request the `urn:mace:dir:entitlement:common-lib-terms` value - which indicates "this user has library access privileges".  And as part of the IdP setup, I have also worked with institutions to make sure their IdP releases the attribute for whoever their Library says should have access (e.g., staff + students).

Hope this helps!

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
This works out fine as suggested by @vladimir-mencl-eresearch 

https://www.dropbox.com/s/h4n2dg2jxp072ny/Screenshot%202017-02-17%2011.51.33.png?dl=0

Another issue solved :).
