### ISSUE TITLE
Validator errors when not-nullable attributes are blank

### ISSUE THREAD

**Issue by abrahad** [ausaccessfed/validator-service#132]
Issue : The validator tool is throwing an error  when IdP is not providing a value for the Display Name.

**Comment by smangelsdorf** [comment]
This also affects email address. Being an attribute validator, we should only rely on a minimum set of attributes (perhaps **only** targeted ID)

**Comment by smangelsdorf** [comment]
Or, in the case where we need more attributes than that, we could be more informative about what went wrong and why it matters.
