### ISSUE TITLE
Logout broken (on Rails 5.2)

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/validator-service#181]
Hi @bradleybeddoes ,

I am running my (DEV) Validator instance at tip of `develop` - so now on Rails 5.2.

And I've noticed Logout stopped working.  If I go through the Logout flow, and go to the landing page again, and go to "Show me my attributes" (`/snapshots/latest`), I get the results page right away, without having to log in again.  (And it's not the SSO flow - I'm watching the browser traffic).

I got it working correctly with:
```
--- a/lib/authentication/subject_receiver.rb
+++ b/lib/authentication/subject_receiver.rb
@@ -40,7 +40,7 @@ module Authentication

     # :nocov:
     def logout(env)
-      env['rack.session'].clear
+      env['rack.session'].destroy

       return redirect_to('/') unless Rails.env.production?

```
However, I'm out of my depth with Rails/Rack here, so I'm filing this as an issue, not a PR.

Also, I don't see the issue at your PROD instance, but I guess it might be it still didn't get the Rails 5.2 upgrade - and that would also hint it's a Rails 5.2 thing.

Can you please confirm whether that makes sense?  Happy to send a PR for it if I get a go-ahead from you.

Cheers,
Vlad

PS: There is another ocurrence of `request.env['rack.session'].clear` in `app/controllers/snapshots_controller.rb` (`failed`), so may need changing as well.

**Comment by rianniello** [comment]
Hi @vladimir-mencl-eresearch, I have been working on the Rails 5.2 upgrade. Thanks for finding this issue. Happy for a PR, thanks!

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the response - just created #183 

Cheers,
Vlad
