### ISSUE TITLE
Service provider compliance differential

### ISSUE THREAD

**Issue by rcaught** [ausaccessfed/validator-service#20]
As an SP I will form a URL that describes all my required attributes.  This URL will hit the identity validator and will inform the subject of what attributes they are missing.

This would be most useful on a failed login page.  URL format should be described in a spec.

**Comment by bradleybeddoes** [comment]
@rcaught: Yes, very hard for a central SP to know the ideosyncrasis of attribute release required by a different SAML SP.

As I can't think of a practical way to implement this for now I am closing this ticket.
