### ISSUE TITLE
Handle new attributes that the validator sees

### ISSUE THREAD

**Issue by rcaught** [ausaccessfed/validator-service#22]
Possible ways to handle are:
- Add to the database, but flag as not enabled (admin will have to)
- Send to a queue for notification (or in conjunction with above)

```
      if FederationAttribute.new_attributes?(attrs.keys)
        # FederationAttribute.new_attributes(attr.keys).each do |attribute|
        #   send_off_to_sqs(attribute)
        # end
      end

```

**Comment by bradleybeddoes** [comment]
I don't believe that the flux of attribute changes or the lack of complexity in doing this via the UI + Ansible PR for the Shibboleth SP has proven to be overly burdensome.

Closing, current approach sufficient.
